name: Ramón Markus Kadi
favicon: null
layout_spectrum: 0.04959955858066678
typography_spectrum: 0.3563668916467577
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#0a0000'
    - '#80482f'
    - '#cad7ce'
    - '#d5ac80'
  brandStrength: 0.5
  lightness: 0.3181687155738473
  saturation: 0.9418701913673431
  rhythmicContrast: 0.75
purpose: []
